# Generated by Django 5.1.5 on 2025-05-20 08:29

import authentification.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', authentification.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('full_address', models.TextField()),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('recipient_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(help_text='Format yang diterima: 081234567890, 6281234567890, atau +6281234567890', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Masukkan nomor yang valid: contoh 081234567890 atau +6281234567890', regex='^(?:\\+62|62|0)8[1-9][0-9]{6,9}$')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
