# Generated by Django 5.1.5 on 2025-05-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charm',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
