# Generated by Django 5.1.5 on 2025-05-26 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('homepage', 'Home Page'), ('new_arrival', 'New Arrival'), ('for_us', 'For Us'), ('for_him', 'For Him'), ('for_her', 'For Her'), ('jewel_set', 'Jewel Set'), ('charmbar', 'Charm Bar'), ('charms', 'Charms'), ('necklace', 'Necklace'), ('bracelet', 'Bracelet'), ('earrings', 'Earrings'), ('rings', 'Rings'), ('anklets', 'Anklets'), ('gift_sets', 'Gift Sets')], max_length=30, unique=True)),
                ('image', models.ImageField(upload_to='banners/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_text', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='photo_gallery/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='charm',
            name='label',
            field=models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('rose_gold', 'Rose Gold'), ('null', 'Null')], default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='charms',
            field=models.BooleanField(default=False, help_text='Apakah produk ini memiliki charms?'),
        ),
        migrations.CreateModel(
            name='DiscountedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage (%)'), ('amount', 'Fixed Amount (Rp)')], max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.discountcampaign')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='api.product')),
            ],
        ),
    ]
