# Generated by Django 5.1.5 on 2025-05-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='gift_set_products',
            new_name='jewel_set_products',
        ),
        migrations.AlterField(
            model_name='pagebanner',
            name='page',
            field=models.CharField(choices=[('homepage', 'Home Page'), ('new_arrival', 'New Arrival'), ('for_us', 'For Us'), ('for_him', 'For Him'), ('for_her', 'For Her'), ('jewel_set', 'Jewel Set'), ('charmbar', 'Charm Bar'), ('charms', 'Charms'), ('necklace', 'Necklace'), ('bracelet', 'Bracelet'), ('earrings', 'Earrings'), ('rings', 'Rings'), ('anklets', 'Anklets'), ('gift_sets', 'Gift Sets'), ('monthly_special', 'Monthly Special')], max_length=30, unique=True),
        ),
    ]
