# Generated by Django 5.1.5 on 2025-05-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_gift_set_products_product_jewel_set_products_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftSetOrBundleMonthlySpecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('label', models.CharField(choices=[('forUs', 'For Us'), ('forHer', 'For Her'), ('forHim', 'For Him'), ('monthlySpecial', 'Monthly Special'), ('null', 'Null')], default='null', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='gift_sets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_monthly_special', models.BooleanField(default=True, help_text='Apakah ini adalah produk spesial bulanan?')),
                ('products', models.ManyToManyField(related_name='gift_sets', to='api.product')),
            ],
        ),
        migrations.DeleteModel(
            name='GiftSet',
        ),
    ]
