# Generated by Django 5.1.5 on 2025-05-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_giftsetorbundlemonthlyspecial_delete_giftset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('necklace', 'Necklace'), ('bracelet', 'Bracelet'), ('earring', 'Earring'), ('ring', 'Ring'), ('anklet', 'Anklet'), ('jewel_set', 'Jewel Set'), ('charm', 'Charm')], max_length=20),
        ),
    ]
