# Generated by Django 5.1.5 on 2025-06-06 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_order_products_remove_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftsetorbundlemonthlyspecial',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='giftsetorbundlemonthlyspecial',
            name='sold_stok',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='giftsetorbundlemonthlyspecial',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.order'),
        ),
    ]
