# Generated by Django 5.1.5 on 2025-06-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_giftsetorbundlemonthlyspecial_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitemcharm',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
