# Generated by Django 5.1.5 on 2025-06-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_cartitemcharm_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_charm_spreadable',
            field=models.BooleanField(default=False, help_text='Apakah produk ini charmsnya bisa disebarkan?'),
        ),
    ]
